###
POST http://localhost:80/admin/data

###
PUT http://localhost:80/orders/5/status
Content-Type: application/json

{
"status": "NEW"
}

### Catalog
GET http://localhost:80/catalog/96

### CoverId
GET http://localhost:80/uploads/90/file


###
GET http://localhost:80/uploads/97

###
POST http://localhost:80/orders
Content-Type: application/json

{
  "items": [
    {
      "bookId": 89,
      "quantity": 1
    },
    {
      "bookId": 12,
      "quantity": 2
    }
  ],
  "recipient": {
    "name": "John Doe",
    "phone": "123-456-789",
    "street": "Cwiartki 3/4",
    "city": "Krakow",
    "zipCode": "30-150",
    "email": "johndoe@example.org"
  }
}

###
GET http://localhost:80/orders/9

###
GET http://localhost:80/orders

###
POST http://localhost:80/admin/initialization
